Transfer a file to your server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,20 +1,16 @@
-#!/bin/env bash
-#This script transfers the file from the client to a server
-using scp.
+#!/usr/bin/env bash
+# This script transfers a file from the client to a server using scp.
 
 if [ "$#" -lt 4 ]; then
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
 fi
 
-FILE_PATH="$1"
-SERVER_IP="$2"
-USERNAME="$3"
-SSH_KEY="$4"
+file_path=$1
+server_ip=$2
+username=$3
+ssh_key=$4
 
-scp -i "$SSH_KEY" -o StrictHostKeyChecking=no
-"$FILE_PATH" "$USERNAME@$SERVER_IP":~/||{echo"Error:
-File transfer failed.";exit 1;}
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/ || { echo "Error: File transfer failed."; exit 1; }
 
-echo"File transferred successfully to
-$username@$server_ip:~/"
+echo "File transferred successfully to $username@$server_ip:~/"
